whole_series_message = 'Are you sure you want the whole series ({0} seasons, {1} episodes total)? [Y \\ N] '
specify_episode_message = 'Please specify a season and an episode, like this: SEASON EPISODE '
invalid_format_message = 'Invalid format.'
clean_message = 'Are you sure you want to remove all the transcripts of the show {0}? [Y \\ N] '
file_format = './output/{0}_s{1:02d}_e{2:02d}'
season_prompt_message = 'Please choose a season (1 - {0}) '
episode_prompt_message = 'Please choose an episode (1 - {0}) '